### ISSUE TITLE
Naming of Components

### ISSUE THREAD

**Issue by enehry** [enehry/eventurs.UI#7]
@NelsonRyan-06 
- Naming of components like button, input, element that are existed on html should double word example, ButtonDefault
![image](https://github.com/enehry/eventurs.UI/assets/29809483/a181fc33-dc64-43b0-b5ad-8e272ecd3091)
- As reference you can follow this guide https://vuejs.org/style-guide/#rule-categories

**Comment by nlsnryn** [comment]
thanks master
